spring.datasource.url=jdbc:postgresql://localhost:5432/canteen_db
spring.datasource.username=kartik
spring.datasource.password=KESCxyz@361111
jwt.secret=K2iUKfT4dwAdaMDLDUx1VUsLB57y9fOkjqJRqetg8AI=
jwt.expiration=86400000
# logging.level.org.springframework.security=DEBUG