spring.datasource.url=jdbc:postgresql://localhost:5432/canteen_db
spring.datasource.username=kartik
spring.datasource.password=KESCxyz@361111
jwt.secret=${JWT_SECRET:this-is-a-fallback-secret-key-minimum-32-chars}
jwt.expiration=86400000
spring.mvc.async.request-timeout=3600000
# logging.level.org.springframework.security=DEBUG